name: Publish Extension

on:
  push:
    branches:
      - main
    paths-ignore: # dont run when changes made to these folders 
      - '.vscode/**'
      - 'examples/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Publish extension
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        pat: ${{ secrets.VSCODE_MARKETPLACE_PAT }}
